FROM mysql:5.7

ENV MYSQL_DATABASE = MessageNatterUsers
ENV MYSQL_USER = MessageNatterUsersService
ENV MYSQL_PASSWORD = MessageNatterUsersService
ENV MYSQL_RANDOM_ROOT_PASSWORD = yes

EXPOSE 3306

CMD ["mysqld"]